### ISSUE TITLE
No peers in dhtget for tracker

### ISSUE THREAD

**Issue by rakoo** [miguelfreitas/twister-core#127]
Getting the value for peers in a given swarm in DHT returns the number of followers but not the actual peers:

```shell
> twisterd dhtget twister tracker m
[
    {
        "p" : {
            "target" : {
                "n" : "twister",
                "r" : "tracker",
                "t" : "m"
            },
            "v" : {
                "followers" : 343
            }
        }
    }
]
```

**Comment by Erkan-Yilmaz** [comment]
in twisterd 0.9.30 I get now below, but the values look "weird":

./twisterd dhtget b0t tracker m
[
    {
        "p" : {
            "target" : {
                "n" : "b0t",
                "r" : "tracker",
                "t" : "m"
            },
            "v" : {
                "followers" : 142,
                "values" : [
                    "\u0005�W�r�",
                    "%�\u0006vr�",
                    ".�V�\u001F�",
                    "E\u001CC\u000Er�",
                    "H\u000B��r�",
                    "N�}�r�",
                    "S�(Y|�",
                    "U�њr�",
                    "X�N\u000B\u000F2",
                    "[�F�C�",
                    "[�F���",
                    "_U.Jr�",
                    "h�\b\u000E`�",
                    "q�e\u0019�",
                    "z���r�",
                    "|+�E\u0014�",
                    "���ur�",
                    "�7��{|",
                    "�>\u0012�1?",
                    "�<��Z�",
                    "�bI@c�",
                    "����r�",
                    "�S�Qr�",
                    "ԁ\u0019�G\t",
                    "ԁ\u0019�r�"
                ],
                "values_size" : 25
            }
        }
    },
    {
        "p" : {
            "target" : {
                "n" : "b0t",
                "r" : "tracker",
                "t" : "m"
            },
            "v" : {
                "followers" : 91,
                "values" : [
                    "\u0005�W�r�",
                    "\u0018��{\f�",
                    "%�\u0006vr�",
                    "%�\u0000S<N",
                    ".�V�\u001F�",
                    "H\u000B��r�",
                    "H��mr�",
                    "N�}�r�",
                    "S�(Y|�",
                    "U�њr�",
                    "[�F�C�",
                    "[�F���",
                    "_U.Jr�",
                    "h�\b\u000E`�",
                    "q�e\u0019�",
                    "���ur�",
                    "�eʓ\u001C]",
                    "�7��{|",
                    "�>\u0012�1?",
                    "�<��Z�",
                    "�bI@c�",
                    "����r�",
                    "�S�Qr�",
                    "ԁ\u0019�G\t",
                    "ԁ\u0019�r�",
                    "���[r�"
                ],
                "values_size" : 26
            }
        }
    }
]

**Comment by miguelfreitas** [comment]
these are binary ip addresses / ports... what would you expect? ;-)

**Comment by Erkan-Yilmaz** [comment]
well, I did not know.
From what you say, all is fine now, and this bug can be closed
