### ISSUE TITLE
Check pieces before sending to other peers in swarm

### ISSUE THREAD

**Issue by miguelfreitas** [miguelfreitas/twister-core#15]
The issue here is that whenever acceptSignedPost is changed to become stricter the old posts (which have been previously accepted into torrents) may fail to pass in the new test. This causes peers to become massively banned by other peers because they try to send invalid pieces.

**Comment by D4708** [comment]
> @Erkan-Yilmaz not related. in fact you noticed a limitation: you cannot RT a promoted post ;-)

the same issue for the favorite posts?
I saw this error also on trying to retwist some posts on the profile review.
