### ISSUE TITLE
how to run as a server?

### ISSUE THREAD

**Issue by gogoqiu** [miguelfreitas/twister-core#305]
example:
raspberry pi(server, twisterd had been built): 192.168.1.150
a notebook: 192.168.1.160

question: how to use the notebook to access the twister by the raspberrypi

**Comment by D4708** [comment]
@gogoqiu following article would be helpful
[Remote Twister Node setup (Ubuntu Debian)](https://github.com/twisterarmy/documentation/wiki/Remote-Twister-Node-setup-(Ubuntu-Debian))
