### ISSUE TITLE
automatically use the html files from the twister-html debian package

### ISSUE THREAD

**Issue by ulrichard** [miguelfreitas/twister-core#309]
After I installed twister from the launchpad ppa, it didn't work.
So I checked out the html from github into ~/.twister 
Later I found out that it was even better to insert 
htmldir=/usr/share/twister/html
into
~/.twister/twister.conf

But I think none of the two should be required to be done by the user.

**Comment by miguelfreitas** [comment]
Good idea. I've just implemented the same logic in twister-control, which is the twister icon that should have been installed along with the package (is it?).

But you're right. There's no reason twisterd itself shouldn't be looking for both directories.
