### ISSUE TITLE
[feature] follower and centos6 rpm

### ISSUE THREAD

**Issue by lanybass** [miguelfreitas/twister-core#314]
why there is no getfollower?
why there is centos7 rpm ?

**Comment by miguelfreitas** [comment]
On Mon, Feb 2, 2015 at 12:39 AM, lanybass <notifications@github.com> wrote:

> why there is no getfollower?
>

See FAQ's "Why can't I see my followers?"

http://twister.net.co/?page_id=25


> why there is centos7 rpm ?
>
>
> See here:

http://twister.net.co/?p=434

Centos 6 is not available due to the boost library version.

regards,

Miguel
