### ISSUE TITLE
"twisterd --help" exits with code 1

### ISSUE THREAD

**Issue by yawara** [miguelfreitas/twister-core#315]

**Comment by Erkan-Yilmaz** [comment]
For me it shows the correct info, see for version 0.9.28 (1).

How (and which version) did you compile twister-core?
Does twister work in general for you? e.g. you can send/read messages from the gui?
Which OS are you on?

(1) http://skilledtests.com/wiki/Twister_commands

**Comment by yawara** [comment]
I complied 0.9.28 on OSX Maverics using clang ( Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn ) ). My build works fine.

I can see version information and help correctly but exit status is only incorrect.
 
```
$ twisterd --help 1>/dev/null; echo $?
1
```

**Comment by yawara** [comment]
If twisterd running, "twisterd help" exit with 0 correctly.

```
$ twisterd -daemon -rpcuser=user -rpcpassword=pwd -rpcallowip=127.0.0.1
Twister server starting
$ twisterd help 1>/dev/null; echo $?
0
$ killall twisterd
$ twisterd help 1>/dev/null; echo $?
error: couldn't connect to server
87
```

**Comment by Erkan-Yilmaz** [comment]
I see, I can confirm what you had also here:

twisterd help 1>/dev/null; echo $?
0

twisterd --help 1>/dev/null; echo $?
1

twisterd help 1>/dev/null; echo $?
error: incorrect rpcuser or rpcpassword (authorization failed)
87

**Comment by miguelfreitas** [comment]
do you want 0 for --help?
we may change that (it should just a matter of replacing "false" for "true" in bitcoind.cpp:60)

**Comment by yawara** [comment]
@miguelfreitas I am writing twister's formula for homebrew, which is a package manager for mac.
https://github.com/Homebrew/homebrew/pull/35442
