### ISSUE TITLE
Error compiling "libtorrent/src/peer_connection.o"

### ISSUE THREAD

**Issue by Epictek** [miguelfreitas/twister-core#319]
``` 
 CXX      libtorrent/src/peer_connection.o
libtorrent/src/peer_connection.cpp: In member function ‘void libtorrent::peer_connection::on_connection_complete(const boost::system::error_code&)’:
libtorrent/src/peer_connection.cpp:5537:24: error: ‘RAND_add’ was not declared in this scope
   RAND_add(&now, 8, 1.5);
                        ^
Makefile:1414: recipe for target 'libtorrent/src/peer_connection.o' failed
make: *** [libtorrent/src/peer_connection.o] Error 1
```

OS is Void Linux

**Comment by miguelfreitas** [comment]
Do you know your openssl version?
RAND_add seems to be available since OpenSSL 0.9.5.

**Comment by Epictek** [comment]
Ah Void used libressl
quick google found me this https://fossies.org/diffs/libressl/2.1.1_vs_2.1.2/man/RAND_add.3-diff.html

**Comment by Epictek** [comment]
Looks like this is a problem with libtorrent still using RAND_add after some googling I found this patch, No idea if it will work but we will see. Will close this issue for now.
http://permalink.gmane.org/gmane.network.bit-torrent.libtorrent/5223
