### ISSUE TITLE
Build failed - src/bitcoinrpc.cpp:1067: undefined reference to `generateRSS(std::string, std::string*)' collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by podshumok** [miguelfreitas/twister-core#343]
Build log

https://launchpadlibrarian.net/213430423/buildlog_ubuntu-vivid-i386.twister-core_0.9%2B2399%2B201508030046~ubuntu15.04.1_BUILDING.txt.gz

**Comment by erqan** [comment]
it was my fault, sorry... #344 should fix it..
