### ISSUE TITLE
Builds for current Fedora versions are missing

### ISSUE THREAD

**Issue by brejoc** [miguelfreitas/twister-core#350]
Seems like the last [supported version of Fedora](http://software.opensuse.org/download.html?project=home%3Amiguelfreitas&package=twister) is [version 20](http://download.opensuse.org/repositories/home:/miguelfreitas/Fedora_20/home:miguelfreitas.repo). The current version is 22 and soon version 23 will be released. Would it cause much trouble to also support more recent versions?

**Comment by miguelfreitas** [comment]
The Fedora package is provided by openSUSE Build Service (https://build.opensuse.org/) and i'm not seeing any other Fedora version there besides 20.

Is this package incompatible with Fedora 22?

**Comment by miguelfreitas** [comment]
ops, it seems i've missed the option to enable new repositories. i'll give it a try.

**Comment by miguelfreitas** [comment]
done. fedora 22 build success.

**Comment by brejoc** [comment]
Thanks! :thumbsup:
