### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by IanSwift** [miguelfreitas/twister-core#351]
Hi,

I found a build error while I was building on OSX last night. On line 1690 of twister.cpp it reads...

    std::string sig = createSignature(std::string(buf.data(),buf.size()), username);
    if( sig.size() ) {
        v["sig_userpost"] = sig;
        return true;
    } else {
        return false;
    }

However, in the parameters for this function, sig is already declared as an Entry object.

    entry const *sig

So I just changed the failing code where it was being reused as a different type to be "sig_" in all three places it is referenced in line 1690, 1691, and 1692. However, I left the blockchain downloading over night, and it never finished. Not sure if I fixed it or broke it. Any thoughts? (Also, my computer went into sleep a couple times, so that might have stopped the download. No logs makes it hard to tell.)

Thanks.

**Comment by IanSwift** [comment]
nvm, the blockchain appeared to have downloaded. But it wouldn't build without the change I made, so you may want to look into that.

**Comment by miguelfreitas** [comment]
thanks!
