### ISSUE TITLE
Spam follow subscribe 

### ISSUE THREAD

**Issue by sbDevGit** [miguelfreitas/twister-core#371]
It seems I see a message from someone without following to the profile
And the profile has a strange number of subscribers
https://ipfs.pics/ipfs/QmSy12rbsT1PvFu1dGUTc95EELUG3jRzPzmKf5Xy2Goq3x

http://127.0.0.1:28332/home.html#profile?user=nobody

**Comment by Tschaul** [comment]
These are so called promoted posts. If a miner finds a block it is allowed to attach a post that is distributed to everyone. Currently most miners keep the default setting where this post is send from the "nobody" account.

Promoted posts are a way of proving that someone has invested cpu resources to secure the blockchain. If you secure the blockchain you are allowed to spam. Currently there is no option not to spam when mining, which i think is needed. Therefore in my client (in developement) "nobody" is blocked by default.

**Comment by sbDevGit** [comment]
Thanks for this useful answer ;)
