### ISSUE TITLE
can't join DMs group back with new wallet.dat

### ISSUE THREAD

**Issue by slr** [miguelfreitas/twister-core#381]
I've deleted my `wallet.dat` once in December 2015 as far as I remember, then created new one and imported my private key back. after that I did rescanning of direct messages. no groups.

inviting by someone else of a group doesn't work: I see all old messages in a group but can't send new ones:
> error encrypting to pubkey of destination user

if I'm leaving and trying to join back via the first section of twister-html's `#groupmessages+joingroup`:

> can't invite tasty to *randomID group — error encrypting to pubkey of group alias

the second section of that doesn't work because joining via `importprivkey` is impossible (yep, we try to do it this way for now: https://github.com/miguelfreitas/twister-html/blob/3d92f854101f05d18c0196022399e82230db773e/js/twister_directmsg.js#L369).

so I request  `importprivkeygroupdm` method or something and fixes for all related things.

**Comment by miguelfreitas** [comment]
Ok, I will take a look, implementing this method or something... But I need some time, these are very busy days here...

**Comment by slr** [comment]
@erqan can you help here, please?

**Comment by slr** [comment]
@erqan cool, thanks. what about ` importprivkeygroupdm` (which shoud return group alias btw)?
