### ISSUE TITLE
Autotool.sh problem in Ubuntu 16.10

### ISSUE THREAD

**Issue by podshumok** [miguelfreitas/twister-core#393]
Build log
https://launchpadlibrarian.net/288440454/buildlog_ubuntu-yakkety-amd64.twister-core_0.9+2438+201610052232~ubuntu16.10.1_BUILDING.txt.gz

Problem is here:
https://github.com/miguelfreitas/twister-core/blob/master/autotool.sh#L51
there is nothing to shift

**Comment by slr** [comment]
LIBTOOLIZE env variable on Ubuntu 16.10 is empty even though `libtool` is installed.
