### ISSUE TITLE
libboost error during bootstrap.sh compilation on OpenSuSE Tumbleweed similar to #241

### ISSUE THREAD

**Issue by Chewie9999** [miguelfreitas/twister-core#404]
It seems that issue #241 is still a problem when compiling on OpenSuSE Tumbleweed (20170605).

I get libboost errors when trying to compile, even though they are installed.
This was using the current (as of 30mins ago) git repository.
Downloading the 2 .m4 scripts referenced in the other issue seemed to fix the problem.

**Comment by miguelfreitas** [comment]
Thanks for the report! I'm updating the m4 on our repo now.
