### ISSUE TITLE
Ubuntu 20 compiling error

### ISSUE THREAD

**Issue by christianriley** [miguelfreitas/twister-core#435]
Compiling on Ubuntu 20 fails as below.  Has anyone succeeded?

  CXX      libtorrent/src/web_connection_base.o
In file included from ./libtorrent/include/libtorrent/peer_connection.hpp:66,
                 from ./libtorrent/include/libtorrent/web_connection_base.hpp:60,
                 from libtorrent/src/web_connection_base.cpp:40:
./libtorrent/include/libtorrent/alert.hpp:116:16: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
  116 |   virtual std::auto_ptr<alert> clone() const = 0;
      |                ^~~~~~~~
In file included from /usr/include/c++/9/memory:80,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/get_pointer.hpp:14,
                 from /usr/include/boost/bind/mem_fn.hpp:25,
                 from /usr/include/boost/mem_fn.hpp:22,
                 from /usr/include/boost/bind/bind.hpp:26,
                 from /usr/include/boost/bind.hpp:22,
                 from libtorrent/src/web_connection_base.cpp:37:
/usr/include/c++/9/bits/unique_ptr.h:53:28: note: declared here
   53 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
In file included from ./libtorrent/include/libtorrent/peer_connection.hpp:66,
                 from ./libtorrent/include/libtorrent/web_connection_base.hpp:60,
                 from libtorrent/src/web_connection_base.cpp:40:
./libtorrent/include/libtorrent/alert.hpp:136:15: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
  136 |    const std::auto_ptr<alert>& alert_, const Handler& handler
      |               ^~~~~~~~
In file included from /usr/include/c++/9/memory:80,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/get_pointer.hpp:14,
                 from /usr/include/boost/bind/mem_fn.hpp:25,
                 from /usr/include/boost/mem_fn.hpp:22,
                 from /usr/include/boost/bind/bind.hpp:26,
                 from /usr/include/boost/bind.hpp:22,
                 from libtorrent/src/web_connection_base.cpp:37:
/usr/include/c++/9/bits/unique_ptr.h:53:28: note: declared here
   53 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
In file included from ./libtorrent/include/libtorrent/peer_connection.hpp:66,
                 from ./libtorrent/include/libtorrent/web_connection_base.hpp:60,
                 from libtorrent/src/web_connection_base.cpp:40:
./libtorrent/include/libtorrent/alert.hpp:150:15: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
  150 |    const std::auto_ptr<alert>&
      |               ^~~~~~~~
In file included from /usr/include/c++/9/memory:80,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/get_pointer.hpp:14,
                 from /usr/include/boost/bind/mem_fn.hpp:25,
                 from /usr/include/boost/mem_fn.hpp:22,
                 from /usr/include/boost/bind/bind.hpp:26,
                 from /usr/include/boost/bind.hpp:22,
                 from libtorrent/src/web_connection_base.cpp:37:
/usr/include/c++/9/bits/unique_ptr.h:53:28: note: declared here
   53 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
In file included from ./libtorrent/include/libtorrent/peer_connection.hpp:66,
                 from ./libtorrent/include/libtorrent/web_connection_base.hpp:60,
                 from libtorrent/src/web_connection_base.cpp:40:
./libtorrent/include/libtorrent/alert.hpp:165:27: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
  165 |   handle_alert(const std::auto_ptr<alert>& alert_
      |                           ^~~~~~~~
In file included from /usr/include/c++/9/memory:80,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/get_pointer.hpp:14,
                 from /usr/include/boost/bind/mem_fn.hpp:25,
                 from /usr/include/boost/mem_fn.hpp:22,
                 from /usr/include/boost/bind/bind.hpp:26,
                 from /usr/include/boost/bind.hpp:22,
                 from libtorrent/src/web_connection_base.cpp:37:
/usr/include/c++/9/bits/unique_ptr.h:53:28: note: declared here
   53 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
...continues

**Comment by Chocobo1** [comment]
I've submitted PR #438, could you please give it a try?
