### ISSUE TITLE
Website copyrights and content usage

### ISSUE THREAD

**Issue by D4708** [miguelfreitas/twister-core#447]
I want to support the official twister project by the @twisterarmy community and it future resources.

Not found official website sources on GitHub, so my question is can we use some twister.net.co website content and branding media (eg twister logo, app screenshots) to create new community-based unofficial website (documentation/f.a.q./guides e.t.c.)? If yes, which license should be inherited?

Related subject: https://github.com/twisterarmy/website/issues/1
Our road-map: https://github.com/orgs/twisterarmy/projects/1

Community owners: @d4708, @myleneb

**Comment by miguelfreitas** [comment]
You may please consider CC license for all twister.net.com contents.
Sure, no problem using the branding media and stuff!

**Comment by D4708** [comment]
As I understand, you meant most common CC BY licence type. Thanks for your attention.

https://creativecommons.org/licenses
